# Generated by Django 3.2.9 on 2021-12-02 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date_upload',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
