# Generated by Django 3.2.9 on 2021-12-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_date_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
